export default {
  addresses: [],
  clients: [],
  cities: [],
  subdivisions: [],
  contacts: [],
  jobnumberseqs: [],
  stateLookup: [],
  countryLookup: [],
  roleLookup: [],
  session: {
    user_id: null,
    username: "",
    auth_key: "",
    authenticated: false,
    token: "",
    contact_id: null,
    first_name: "",
    full_name: "",
    role: "",
    client_id: null,
    client_name: ""
  },
  message: {
    ok: true,
    type: "",
    status: null,
    title: "",
    content: ""
  },
  showClientDialog: false,
  showContactDialog: false,
  showSubdivisionDialog: false,
  showCityDialog: false,
};
