export default {
  addresses: [],
  search: {
    recents: '1',
    recentsResults: [],
    find: null,
    findResults: [],
  },
  dups: [],
  clients: [],
  cities: [],
  subdivisions: [],
  contacts: [],
  requestors: [], // subset of contacts where requestor = 'Y'
  jobnumberseqs: [],
  stateLookup: [],
  countryLookup: [],
  roleLookup: [],
  trelloListLookup: [],
  recordStatusLookup: [],
  projectStatusLookup: [],
  scopeLookup: [],
  classificationLookup: [],
  masonryLookup: [],
  ynLookup: [],
  fndTypeLookup: [],
  garageTypeLookup: [],
  garageEntryLookup: [],
  garageSwingLookup: [],
  floorTypeLookup: [],
  roofTypeLookup: [],
  coveredPatioLookup: [],
  dwellingTypeLookup: [],
  pitaLookup: [],
  geos: [],
  geoMasterData: [],
  session: {
    authInProgress: true,
    id: null,
    username: "",
    auth_key: "",
    approved: '',
    authenticated: false,
    token: "",
    contact_id: null,
    first_name: "",
    full_name: "",
    role: "",
    client_id: null,
    client_name: "",
    currentMenuID: null,
    userSettings: {
      accent_color: '#42a5f5',
    },
  },
  message: {
    ok: true,
    type: "",
    status: null,
    title: "",
    content: ""
  },
  showClientDialog: false,
  showContactDialog: false,
  showSubdivisionDialog: false,
  showCityDialog: false,
  avffControls:[],
  avffRelationships:[],
  currentMenu: {},
  currentViews: [],  // could load multiple views.  SINGLE view is default.
  currentProject: {},
  saveType: [
    {name: 'save', code: 'save'},
    {name: 'commit', code: 'commit'}
  ]

};
